### ISSUE TITLE
why is there no Linux version?

### ISSUE THREAD

**Issue by candrapersada** [DiskPro/Youtube-DL-GUI#3]
why does Youtube-DL-GUI not have a Linux version?

**Comment by gfrn** [comment]
Hello!

As of now, I'm busy with work, school and other activities as well, so I don't have much time left to work on porting the code through and through.  However, some of my friends do have an interest in porting it to Electron and I'll be seeing with them how their progress is going.  

That means I don't plan on porting it to Linux any time soon, but you'll be able to find similar tools online fairly easily. Thank you for your interest!

I'll be closing this issue if there aren't any other questions, feel free to reopen it if necessary.
