### ISSUE TITLE
how to merge video and audio?

### ISSUE THREAD

**Issue by candrapersada** [DiskPro/Youtube-DL-GUI#4]
how to download and merge webm (DASH) and m4a (audio)?
and how to download youtube playlist?

**Comment by gfrn** [comment]
Sorry for the late reply. You can download a Youtube playlist by pasting in the playlist URL, selecting a format, adding to queue and downloading. As for merging audio and video, there indeed was a problem, but it's fixed now. 

You should be able to select a video, click on "merge audio and video", then select a video and click "convert".
